import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import 'leaflet/dist/leaflet.css';
// import 'react-leaflet-search/dist/styles.css'; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <div className="flex h-screen">
      <Sidebar />
      <div className="flex-1 bg-white">
        {children}
      </div>
    </div>
        </body>
    </html>
  );
}
