import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import AuthenticatedLayout from '@/components/AuthenticatedLayout';

// import 'react-leaflet-search/dist/styles.css'; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <AuthenticatedLayout>
            {children}
          </AuthenticatedLayout>
        </body>
      </UserProvider>
    </html>
  );
}
